version: "3"
services:
  server:
    image: mvilche/redash:8-alpine
    depends_on:
      - redis
      - database-redash
    volumes:
      - redash:/opt/redash/datainit
    command: server
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://redash:password@database-redash/redash"
      REDASH_RATELIMIT_ENABLED: "false"
      GOOGLE_OAUTH_ENABLED: "true"
    ports:
      - "8182:5000"

  worker:
    image: mvilche/redash:8-alpine
    command: worker
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://redash:password@database-redash/redash"
      QUEUES: "queries,scheduled_queries,celery,schemas"
      WORKERS_COUNT: 2

  scheduler:
    image: mvilche/redash:8-alpine
    command: scheduler
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://redash:password@database-redash/redash"
      QUEUES: "queries,scheduled_queries,celery,schemas"
      WORKERS_COUNT: 2      

  redis:
    image: redis:alpine

  database-redash:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=redash
      - POSTGRES_DB=redash
    volumes:
      - postgres-redash:/var/lib/postgresql/data

  waf:
    image: mvilche/modsecurity:centos7-v3.1.0
    environment:
     - SERVERNAME=redash.local
     - PROXY_IP=server
     - PROXY_PORT=5000
     - PROTOCOL_PROXY=http
     - MODSECURITY_STATUS=Off
    ports:
     - "443:8443"

volumes:
  postgres-redash:
  redash:
